# This is a basic workflow to help you get started with Actions

name: Class1Bootcamp2020

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Installing Node Module
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12  


    # Runs a set of commands using the runners shell
    - name: Installing surge
      run: npm  install --global surge
       # Runs a set of commands using the runners shell
    - name: Deploying using surge
       #ab humnesuge install krlia h so we should name our website wo  bhi dedi name bhi dedia but github is a 3rd party tool so hume surge ko access krne k lye login krna parta h jo clone wager am nh hopayega
       #so we have to give it token jo khud phle generate krna prega ab token agya toh ya m toh direct copy best krdo but it is not best practice
      # run: surge ./  class1bootcamp.surge.sh --token "e91d1230e61dc27f793e6d2ef02a5acf" yeh sahi nh h krna par
        #ap is ko secret krde toekn ko
      run: surge ./ class1bootcamp.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      
   
      
  
      
      
      
      
      
